name: dry-files
codacy_id: codacy-id
gemspec:
  authors: ["Luca Guidi"]
  email: ["me@lucaguidi.com"]
  summary: "file utilities"
  development_dependencies:
    - ['rake', '~> 13.0']
    - ['rspec', '~> 3.10']
    - ['rubocop', '~> 1.12']
